# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = ["resume_offset=50191960"];
  boot.resumeDevice = "/dev/disk/by-uuid/78296245-c79a-4f7d-ac27-deba8ab44d63";
  powerManagement.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/78296245-c79a-4f7d-ac27-deba8ab44d63";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/34F7-6F5A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/78296245-c79a-4f7d-ac27-deba8ab44d63";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/78296245-c79a-4f7d-ac27-deba8ab44d63";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/78296245-c79a-4f7d-ac27-deba8ab44d63";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 200 * 1024; # 32GB in MB
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
